// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type Coach struct {
	FutbolistaID    int64
	ExperienceYears sql.NullInt32
}

type Futbolistum struct {
	ID          int64
	TeamID      sql.NullInt64
	Name        string
	Number      sql.NullInt32
	YearsInTeam sql.NullInt32
}

type Player struct {
	FutbolistaID  int64
	PositionID    sql.NullInt64
	MatchesPlayed sql.NullInt32
	Goals         sql.NullInt32
	Assists       sql.NullInt32
}

type Position struct {
	ID   int64
	Name string
}

type Season struct {
	ID        int64
	StartDate sql.NullTime
	EndDate   sql.NullTime
}

type Stadium struct {
	ID       int64
	Name     string
	Capacity sql.NullInt32
}

type Team struct {
	ID                  int64
	Name                string
	Province            sql.NullString
	Mascot              sql.NullString
	Color               sql.NullString
	ChampionshipsPlayed sql.NullInt32
	ChampionshipsWon    sql.NullInt32
}
