// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"time"
)

type Coach struct {
	FootballerID     int64
	ExperienceYears  sql.NullInt32
	ChampionshipsWon sql.NullInt32
}

type Footballer struct {
	ID          int64
	TeamID      sql.NullInt64
	Name        string
	Number      sql.NullInt32
	YearsInTeam sql.NullInt32
}

type Match struct {
	ID         int64
	HomeTeamID sql.NullInt64
	AwayTeamID sql.NullInt64
	SeasonID   sql.NullInt64
	StadiumID  sql.NullInt64
	MatchDate  time.Time
	Attendance sql.NullInt32
	Disputed   bool
}

type Player struct {
	FootballerID int64
	Position     string
}

type Playerstat struct {
	ID              int64
	PlayerID        sql.NullInt64
	MatchID         sql.NullInt64
	GoalsScored     sql.NullInt32
	Assists         sql.NullInt32
	ShotsOnGoal     sql.NullInt32
	PassesCompleted sql.NullInt32
	Interceptions   sql.NullInt32
	Tackles         sql.NullInt32
	Blocks          sql.NullInt32
	Saves           sql.NullInt32
	GoalsConceded   sql.NullInt32
}

type Season struct {
	ID        int64
	StartDate sql.NullTime
	EndDate   sql.NullTime
}

type Stadium struct {
	ID       int64
	Name     string
	Capacity sql.NullInt32
}

type Team struct {
	ID                  int64
	Name                string
	Province            sql.NullString
	Mascot              sql.NullString
	Color               sql.NullString
	ChampionshipsPlayed sql.NullInt32
	ChampionshipsWon    sql.NullInt32
	PlayersCount        sql.NullInt32
	CoachesCount        sql.NullInt32
}
