// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createCoach = `-- name: CreateCoach :one
WITH ins_fut AS (
    INSERT INTO Footballer (team_id, name, number, years_in_team)
    VALUES ($1, $2, $3, $4)
    RETURNING id
)
INSERT INTO Coach (footballer_id, experience_years, championships_won)
SELECT id, $5, $6 FROM ins_fut
RETURNING footballer_id
`

type CreateCoachParams struct {
	TeamID           sql.NullInt64
	Name             string
	Number           sql.NullInt32
	YearsInTeam      sql.NullInt32
	ExperienceYears  sql.NullInt32
	ChampionshipsWon sql.NullInt32
}

// Coach CRUD
func (q *Queries) CreateCoach(ctx context.Context, arg CreateCoachParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCoach,
		arg.TeamID,
		arg.Name,
		arg.Number,
		arg.YearsInTeam,
		arg.ExperienceYears,
		arg.ChampionshipsWon,
	)
	var footballer_id int64
	err := row.Scan(&footballer_id)
	return footballer_id, err
}

const createFootballer = `-- name: CreateFootballer :one
INSERT INTO Footballer (team_id, name, number, years_in_team)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateFootballerParams struct {
	TeamID      sql.NullInt64
	Name        string
	Number      sql.NullInt32
	YearsInTeam sql.NullInt32
}

// Footballer (internal, used by Player/Coach)
func (q *Queries) CreateFootballer(ctx context.Context, arg CreateFootballerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createFootballer,
		arg.TeamID,
		arg.Name,
		arg.Number,
		arg.YearsInTeam,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createMatch = `-- name: CreateMatch :one
INSERT INTO Match (home_team_id, away_team_id, season_id, stadium_id, match_date, attendance, disputed)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateMatchParams struct {
	HomeTeamID sql.NullInt64
	AwayTeamID sql.NullInt64
	SeasonID   sql.NullInt64
	StadiumID  sql.NullInt64
	MatchDate  time.Time
	Attendance sql.NullInt32
	Disputed   bool
}

// Match CRUD
func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createMatch,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.SeasonID,
		arg.StadiumID,
		arg.MatchDate,
		arg.Attendance,
		arg.Disputed,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createPlayer = `-- name: CreatePlayer :one
WITH ins_fut AS (
    INSERT INTO Footballer (team_id, name, number, years_in_team)
    VALUES ($1, $2, $3, $4)
    RETURNING id
)
INSERT INTO Player (footballer_id, position)
SELECT id, $5 FROM ins_fut
RETURNING footballer_id
`

type CreatePlayerParams struct {
	TeamID      sql.NullInt64
	Name        string
	Number      sql.NullInt32
	YearsInTeam sql.NullInt32
	Position    string
}

// Player CRUD
func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createPlayer,
		arg.TeamID,
		arg.Name,
		arg.Number,
		arg.YearsInTeam,
		arg.Position,
	)
	var footballer_id int64
	err := row.Scan(&footballer_id)
	return footballer_id, err
}

const createPlayerStat = `-- name: CreatePlayerStat :one
INSERT INTO PlayerStats (
    player_id,
    match_id,
    goals_scored,
    assists,
    shots_on_goal,
    passes_completed,
    interceptions,
    tackles,
    blocks,
    saves,
    goals_conceded
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type CreatePlayerStatParams struct {
	PlayerID        sql.NullInt64
	MatchID         sql.NullInt64
	GoalsScored     sql.NullInt32
	Assists         sql.NullInt32
	ShotsOnGoal     sql.NullInt32
	PassesCompleted sql.NullInt32
	Interceptions   sql.NullInt32
	Tackles         sql.NullInt32
	Blocks          sql.NullInt32
	Saves           sql.NullInt32
	GoalsConceded   sql.NullInt32
}

// PlayerStats CRUD
func (q *Queries) CreatePlayerStat(ctx context.Context, arg CreatePlayerStatParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createPlayerStat,
		arg.PlayerID,
		arg.MatchID,
		arg.GoalsScored,
		arg.Assists,
		arg.ShotsOnGoal,
		arg.PassesCompleted,
		arg.Interceptions,
		arg.Tackles,
		arg.Blocks,
		arg.Saves,
		arg.GoalsConceded,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSeason = `-- name: CreateSeason :one
INSERT INTO Season (start_date, end_date)
VALUES ($1, $2)
RETURNING id
`

type CreateSeasonParams struct {
	StartDate sql.NullTime
	EndDate   sql.NullTime
}

// Season CRUD
func (q *Queries) CreateSeason(ctx context.Context, arg CreateSeasonParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSeason, arg.StartDate, arg.EndDate)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createStadium = `-- name: CreateStadium :one
INSERT INTO Stadium (name, capacity)
VALUES ($1, $2)
RETURNING id
`

type CreateStadiumParams struct {
	Name     string
	Capacity sql.NullInt32
}

// Stadium CRUD
func (q *Queries) CreateStadium(ctx context.Context, arg CreateStadiumParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createStadium, arg.Name, arg.Capacity)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO Team (name, province, mascot, color, championships_played, championships_won)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateTeamParams struct {
	Name                string
	Province            sql.NullString
	Mascot              sql.NullString
	Color               sql.NullString
	ChampionshipsPlayed sql.NullInt32
	ChampionshipsWon    sql.NullInt32
}

// Team CRUD
func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTeam,
		arg.Name,
		arg.Province,
		arg.Mascot,
		arg.Color,
		arg.ChampionshipsPlayed,
		arg.ChampionshipsWon,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteCoachRecord = `-- name: DeleteCoachRecord :exec
DELETE FROM Coach WHERE footballer_id = $1
`

func (q *Queries) DeleteCoachRecord(ctx context.Context, footballerID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCoachRecord, footballerID)
	return err
}

const deleteFootballer = `-- name: DeleteFootballer :exec
DELETE FROM Footballer WHERE id = $1
`

func (q *Queries) DeleteFootballer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFootballer, id)
	return err
}

const deleteMatch = `-- name: DeleteMatch :exec
DELETE FROM Match WHERE id = $1
`

func (q *Queries) DeleteMatch(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMatch, id)
	return err
}

const deletePlayerRecord = `-- name: DeletePlayerRecord :exec
DELETE FROM Player WHERE footballer_id = $1
`

func (q *Queries) DeletePlayerRecord(ctx context.Context, footballerID int64) error {
	_, err := q.db.ExecContext(ctx, deletePlayerRecord, footballerID)
	return err
}

const deletePlayerStat = `-- name: DeletePlayerStat :exec
DELETE FROM PlayerStats WHERE id = $1
`

func (q *Queries) DeletePlayerStat(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePlayerStat, id)
	return err
}

const deleteSeason = `-- name: DeleteSeason :exec
DELETE FROM Season WHERE id = $1
`

func (q *Queries) DeleteSeason(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSeason, id)
	return err
}

const deleteStadium = `-- name: DeleteStadium :exec
DELETE FROM Stadium WHERE id = $1
`

func (q *Queries) DeleteStadium(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStadium, id)
	return err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM Team WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTeam, id)
	return err
}

const getBestDefender = `-- name: GetBestDefender :one
SELECT
    'Defensa' AS position,
    f.name AS player_name,
    COALESCE(t.name, '') AS team_name,
    'tackles_plus_blocks' AS metric_name,
    COALESCE(SUM(ps.tackles + ps.blocks), 0) AS metric_value,
    COALESCE(SUM(ps.goals_scored), 0) AS goals_scored,
    COALESCE(SUM(ps.assists), 0) AS assists,
    COALESCE(SUM(ps.shots_on_goal), 0) AS shots_on_goal,
    COALESCE(SUM(ps.passes_completed), 0) AS passes_completed,
    COALESCE(SUM(ps.interceptions), 0) AS interceptions,
    COALESCE(SUM(ps.tackles), 0) AS tackles,
    COALESCE(SUM(ps.blocks), 0) AS blocks,
    COALESCE(SUM(ps.saves), 0) AS saves,
    COALESCE(SUM(ps.goals_conceded), 0) AS goals_conceded
FROM Footballer f
JOIN Player p ON p.footballer_id = f.id
JOIN PlayerStats ps ON ps.player_id = p.footballer_id
JOIN Match m ON m.id = ps.match_id
LEFT JOIN Team t ON t.id = f.team_id
WHERE p.position = 'Defensa' AND m.season_id = $1
GROUP BY f.id, f.name, t.name
ORDER BY metric_value DESC, tackles DESC, blocks DESC, f.name
LIMIT 1
`

type GetBestDefenderRow struct {
	Position        string
	PlayerName      string
	TeamName        string
	MetricName      string
	MetricValue     interface{}
	GoalsScored     interface{}
	Assists         interface{}
	ShotsOnGoal     interface{}
	PassesCompleted interface{}
	Interceptions   interface{}
	Tackles         interface{}
	Blocks          interface{}
	Saves           interface{}
	GoalsConceded   interface{}
}

func (q *Queries) GetBestDefender(ctx context.Context, seasonID sql.NullInt64) (GetBestDefenderRow, error) {
	row := q.db.QueryRowContext(ctx, getBestDefender, seasonID)
	var i GetBestDefenderRow
	err := row.Scan(
		&i.Position,
		&i.PlayerName,
		&i.TeamName,
		&i.MetricName,
		&i.MetricValue,
		&i.GoalsScored,
		&i.Assists,
		&i.ShotsOnGoal,
		&i.PassesCompleted,
		&i.Interceptions,
		&i.Tackles,
		&i.Blocks,
		&i.Saves,
		&i.GoalsConceded,
	)
	return i, err
}

const getBestForward = `-- name: GetBestForward :one
SELECT
    'Delantero' AS position,
    f.name AS player_name,
    COALESCE(t.name, '') AS team_name,
    'shots_on_goal' AS metric_name,
    COALESCE(SUM(ps.shots_on_goal), 0) AS metric_value,
    COALESCE(SUM(ps.goals_scored), 0) AS goals_scored,
    COALESCE(SUM(ps.assists), 0) AS assists,
    COALESCE(SUM(ps.shots_on_goal), 0) AS shots_on_goal,
    COALESCE(SUM(ps.passes_completed), 0) AS passes_completed,
    COALESCE(SUM(ps.interceptions), 0) AS interceptions,
    COALESCE(SUM(ps.tackles), 0) AS tackles,
    COALESCE(SUM(ps.blocks), 0) AS blocks,
    COALESCE(SUM(ps.saves), 0) AS saves,
    COALESCE(SUM(ps.goals_conceded), 0) AS goals_conceded
FROM Footballer f
JOIN Player p ON p.footballer_id = f.id
JOIN PlayerStats ps ON ps.player_id = p.footballer_id
JOIN Match m ON m.id = ps.match_id
LEFT JOIN Team t ON t.id = f.team_id
WHERE p.position = 'Delantero' AND m.season_id = $1
GROUP BY f.id, f.name, t.name
ORDER BY metric_value DESC, goals_scored DESC, assists DESC, f.name
LIMIT 1
`

type GetBestForwardRow struct {
	Position        string
	PlayerName      string
	TeamName        string
	MetricName      string
	MetricValue     interface{}
	GoalsScored     interface{}
	Assists         interface{}
	ShotsOnGoal     interface{}
	PassesCompleted interface{}
	Interceptions   interface{}
	Tackles         interface{}
	Blocks          interface{}
	Saves           interface{}
	GoalsConceded   interface{}
}

// Report 7: all-star team
func (q *Queries) GetBestForward(ctx context.Context, seasonID sql.NullInt64) (GetBestForwardRow, error) {
	row := q.db.QueryRowContext(ctx, getBestForward, seasonID)
	var i GetBestForwardRow
	err := row.Scan(
		&i.Position,
		&i.PlayerName,
		&i.TeamName,
		&i.MetricName,
		&i.MetricValue,
		&i.GoalsScored,
		&i.Assists,
		&i.ShotsOnGoal,
		&i.PassesCompleted,
		&i.Interceptions,
		&i.Tackles,
		&i.Blocks,
		&i.Saves,
		&i.GoalsConceded,
	)
	return i, err
}

const getBestGoalkeeper = `-- name: GetBestGoalkeeper :one
SELECT
    'Portero' AS position,
    f.name AS player_name,
    COALESCE(t.name, '') AS team_name,
    'saves_minus_goals_conceded' AS metric_name,
    COALESCE(SUM(ps.saves - ps.goals_conceded), 0) AS metric_value,
    COALESCE(SUM(ps.goals_scored), 0) AS goals_scored,
    COALESCE(SUM(ps.assists), 0) AS assists,
    COALESCE(SUM(ps.shots_on_goal), 0) AS shots_on_goal,
    COALESCE(SUM(ps.passes_completed), 0) AS passes_completed,
    COALESCE(SUM(ps.interceptions), 0) AS interceptions,
    COALESCE(SUM(ps.tackles), 0) AS tackles,
    COALESCE(SUM(ps.blocks), 0) AS blocks,
    COALESCE(SUM(ps.saves), 0) AS saves,
    COALESCE(SUM(ps.goals_conceded), 0) AS goals_conceded
FROM Footballer f
JOIN Player p ON p.footballer_id = f.id
JOIN PlayerStats ps ON ps.player_id = p.footballer_id
JOIN Match m ON m.id = ps.match_id
LEFT JOIN Team t ON t.id = f.team_id
WHERE p.position = 'Portero' AND m.season_id = $1
GROUP BY f.id, f.name, t.name
ORDER BY metric_value DESC, saves DESC, goals_conceded ASC, f.name
LIMIT 1
`

type GetBestGoalkeeperRow struct {
	Position        string
	PlayerName      string
	TeamName        string
	MetricName      string
	MetricValue     interface{}
	GoalsScored     interface{}
	Assists         interface{}
	ShotsOnGoal     interface{}
	PassesCompleted interface{}
	Interceptions   interface{}
	Tackles         interface{}
	Blocks          interface{}
	Saves           interface{}
	GoalsConceded   interface{}
}

func (q *Queries) GetBestGoalkeeper(ctx context.Context, seasonID sql.NullInt64) (GetBestGoalkeeperRow, error) {
	row := q.db.QueryRowContext(ctx, getBestGoalkeeper, seasonID)
	var i GetBestGoalkeeperRow
	err := row.Scan(
		&i.Position,
		&i.PlayerName,
		&i.TeamName,
		&i.MetricName,
		&i.MetricValue,
		&i.GoalsScored,
		&i.Assists,
		&i.ShotsOnGoal,
		&i.PassesCompleted,
		&i.Interceptions,
		&i.Tackles,
		&i.Blocks,
		&i.Saves,
		&i.GoalsConceded,
	)
	return i, err
}

const getBestMidfielder = `-- name: GetBestMidfielder :one
SELECT
    'Mediocampista' AS position,
    f.name AS player_name,
    COALESCE(t.name, '') AS team_name,
    'passes_completed_plus_interceptions' AS metric_name,
    COALESCE(SUM(ps.passes_completed + ps.interceptions), 0) AS metric_value,
    COALESCE(SUM(ps.goals_scored), 0) AS goals_scored,
    COALESCE(SUM(ps.assists), 0) AS assists,
    COALESCE(SUM(ps.shots_on_goal), 0) AS shots_on_goal,
    COALESCE(SUM(ps.passes_completed), 0) AS passes_completed,
    COALESCE(SUM(ps.interceptions), 0) AS interceptions,
    COALESCE(SUM(ps.tackles), 0) AS tackles,
    COALESCE(SUM(ps.blocks), 0) AS blocks,
    COALESCE(SUM(ps.saves), 0) AS saves,
    COALESCE(SUM(ps.goals_conceded), 0) AS goals_conceded
FROM Footballer f
JOIN Player p ON p.footballer_id = f.id
JOIN PlayerStats ps ON ps.player_id = p.footballer_id
JOIN Match m ON m.id = ps.match_id
LEFT JOIN Team t ON t.id = f.team_id
WHERE p.position = 'Mediocampista' AND m.season_id = $1
GROUP BY f.id, f.name, t.name
ORDER BY metric_value DESC, passes_completed DESC, interceptions DESC, f.name
LIMIT 1
`

type GetBestMidfielderRow struct {
	Position        string
	PlayerName      string
	TeamName        string
	MetricName      string
	MetricValue     interface{}
	GoalsScored     interface{}
	Assists         interface{}
	ShotsOnGoal     interface{}
	PassesCompleted interface{}
	Interceptions   interface{}
	Tackles         interface{}
	Blocks          interface{}
	Saves           interface{}
	GoalsConceded   interface{}
}

func (q *Queries) GetBestMidfielder(ctx context.Context, seasonID sql.NullInt64) (GetBestMidfielderRow, error) {
	row := q.db.QueryRowContext(ctx, getBestMidfielder, seasonID)
	var i GetBestMidfielderRow
	err := row.Scan(
		&i.Position,
		&i.PlayerName,
		&i.TeamName,
		&i.MetricName,
		&i.MetricValue,
		&i.GoalsScored,
		&i.Assists,
		&i.ShotsOnGoal,
		&i.PassesCompleted,
		&i.Interceptions,
		&i.Tackles,
		&i.Blocks,
		&i.Saves,
		&i.GoalsConceded,
	)
	return i, err
}

const getCoach = `-- name: GetCoach :one
SELECT f.id, f.team_id, f.name, f.number, f.years_in_team,
       c.experience_years, c.championships_won
FROM Footballer f
JOIN Coach c ON c.footballer_id = f.id
WHERE f.id = $1
`

type GetCoachRow struct {
	ID               int64
	TeamID           sql.NullInt64
	Name             string
	Number           sql.NullInt32
	YearsInTeam      sql.NullInt32
	ExperienceYears  sql.NullInt32
	ChampionshipsWon sql.NullInt32
}

func (q *Queries) GetCoach(ctx context.Context, id int64) (GetCoachRow, error) {
	row := q.db.QueryRowContext(ctx, getCoach, id)
	var i GetCoachRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Number,
		&i.YearsInTeam,
		&i.ExperienceYears,
		&i.ChampionshipsWon,
	)
	return i, err
}

const getFootballer = `-- name: GetFootballer :one
SELECT id, team_id, name, number, years_in_team FROM Footballer WHERE id = $1
`

func (q *Queries) GetFootballer(ctx context.Context, id int64) (Footballer, error) {
	row := q.db.QueryRowContext(ctx, getFootballer, id)
	var i Footballer
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Number,
		&i.YearsInTeam,
	)
	return i, err
}

const getFootballersByTeam = `-- name: GetFootballersByTeam :many
SELECT id, team_id, name, number, years_in_team
FROM Footballer
WHERE team_id = $1
ORDER BY id
`

// Validation queries
func (q *Queries) GetFootballersByTeam(ctx context.Context, teamID sql.NullInt64) ([]Footballer, error) {
	rows, err := q.db.QueryContext(ctx, getFootballersByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Footballer
	for rows.Next() {
		var i Footballer
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Number,
			&i.YearsInTeam,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatch = `-- name: GetMatch :one
SELECT
    m.id, m.home_team_id, m.away_team_id, m.season_id, m.stadium_id, m.match_date, m.attendance, m.disputed,
    CAST(COALESCE(hg.total, 0) AS INT) AS home_goals,
    CAST(COALESCE(ag.total, 0) AS INT) AS away_goals
FROM Match m
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.home_team_id
) hg ON true
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.away_team_id
) ag ON true
WHERE m.id = $1
`

type GetMatchRow struct {
	ID         int64
	HomeTeamID sql.NullInt64
	AwayTeamID sql.NullInt64
	SeasonID   sql.NullInt64
	StadiumID  sql.NullInt64
	MatchDate  time.Time
	Attendance sql.NullInt32
	Disputed   bool
	HomeGoals  int32
	AwayGoals  int32
}

func (q *Queries) GetMatch(ctx context.Context, id int64) (GetMatchRow, error) {
	row := q.db.QueryRowContext(ctx, getMatch, id)
	var i GetMatchRow
	err := row.Scan(
		&i.ID,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.SeasonID,
		&i.StadiumID,
		&i.MatchDate,
		&i.Attendance,
		&i.Disputed,
		&i.HomeGoals,
		&i.AwayGoals,
	)
	return i, err
}

const getMatchesByAwayTeam = `-- name: GetMatchesByAwayTeam :many
SELECT
    m.id, m.home_team_id, m.away_team_id, m.season_id, m.stadium_id, m.match_date, m.attendance, m.disputed,
    CAST(COALESCE(hg.total, 0) AS INT) AS home_goals,
    CAST(COALESCE(ag.total, 0) AS INT) AS away_goals
FROM Match m
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.home_team_id
) hg ON true
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.away_team_id
) ag ON true
WHERE m.away_team_id = $1
ORDER BY m.match_date, m.id
`

type GetMatchesByAwayTeamRow struct {
	ID         int64
	HomeTeamID sql.NullInt64
	AwayTeamID sql.NullInt64
	SeasonID   sql.NullInt64
	StadiumID  sql.NullInt64
	MatchDate  time.Time
	Attendance sql.NullInt32
	Disputed   bool
	HomeGoals  int32
	AwayGoals  int32
}

func (q *Queries) GetMatchesByAwayTeam(ctx context.Context, awayTeamID sql.NullInt64) ([]GetMatchesByAwayTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, getMatchesByAwayTeam, awayTeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMatchesByAwayTeamRow
	for rows.Next() {
		var i GetMatchesByAwayTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.SeasonID,
			&i.StadiumID,
			&i.MatchDate,
			&i.Attendance,
			&i.Disputed,
			&i.HomeGoals,
			&i.AwayGoals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchesByHomeTeam = `-- name: GetMatchesByHomeTeam :many
SELECT
    m.id, m.home_team_id, m.away_team_id, m.season_id, m.stadium_id, m.match_date, m.attendance, m.disputed,
    CAST(COALESCE(hg.total, 0) AS INT) AS home_goals,
    CAST(COALESCE(ag.total, 0) AS INT) AS away_goals
FROM Match m
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.home_team_id
) hg ON true
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.away_team_id
) ag ON true
WHERE m.home_team_id = $1
ORDER BY m.match_date, m.id
`

type GetMatchesByHomeTeamRow struct {
	ID         int64
	HomeTeamID sql.NullInt64
	AwayTeamID sql.NullInt64
	SeasonID   sql.NullInt64
	StadiumID  sql.NullInt64
	MatchDate  time.Time
	Attendance sql.NullInt32
	Disputed   bool
	HomeGoals  int32
	AwayGoals  int32
}

func (q *Queries) GetMatchesByHomeTeam(ctx context.Context, homeTeamID sql.NullInt64) ([]GetMatchesByHomeTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, getMatchesByHomeTeam, homeTeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMatchesByHomeTeamRow
	for rows.Next() {
		var i GetMatchesByHomeTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.SeasonID,
			&i.StadiumID,
			&i.MatchDate,
			&i.Attendance,
			&i.Disputed,
			&i.HomeGoals,
			&i.AwayGoals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayer = `-- name: GetPlayer :one
SELECT f.id, f.team_id, f.name, f.number, f.years_in_team,
       p.position
FROM Footballer f
JOIN Player p ON p.footballer_id = f.id
WHERE f.id = $1
`

type GetPlayerRow struct {
	ID          int64
	TeamID      sql.NullInt64
	Name        string
	Number      sql.NullInt32
	YearsInTeam sql.NullInt32
	Position    string
}

func (q *Queries) GetPlayer(ctx context.Context, id int64) (GetPlayerRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayer, id)
	var i GetPlayerRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Number,
		&i.YearsInTeam,
		&i.Position,
	)
	return i, err
}

const getPlayerStat = `-- name: GetPlayerStat :one
SELECT id, player_id, match_id, goals_scored, assists, shots_on_goal, passes_completed, interceptions, tackles, blocks, saves, goals_conceded
FROM PlayerStats
WHERE id = $1
`

func (q *Queries) GetPlayerStat(ctx context.Context, id int64) (Playerstat, error) {
	row := q.db.QueryRowContext(ctx, getPlayerStat, id)
	var i Playerstat
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.MatchID,
		&i.GoalsScored,
		&i.Assists,
		&i.ShotsOnGoal,
		&i.PassesCompleted,
		&i.Interceptions,
		&i.Tackles,
		&i.Blocks,
		&i.Saves,
		&i.GoalsConceded,
	)
	return i, err
}

const getSeason = `-- name: GetSeason :one
SELECT id, start_date, end_date FROM Season WHERE id = $1
`

func (q *Queries) GetSeason(ctx context.Context, id int64) (Season, error) {
	row := q.db.QueryRowContext(ctx, getSeason, id)
	var i Season
	err := row.Scan(&i.ID, &i.StartDate, &i.EndDate)
	return i, err
}

const getStadium = `-- name: GetStadium :one
SELECT id, name, capacity FROM Stadium WHERE id = $1
`

func (q *Queries) GetStadium(ctx context.Context, id int64) (Stadium, error) {
	row := q.db.QueryRowContext(ctx, getStadium, id)
	var i Stadium
	err := row.Scan(&i.ID, &i.Name, &i.Capacity)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, province, mascot, color, championships_played, championships_won
FROM Team
WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Province,
		&i.Mascot,
		&i.Color,
		&i.ChampionshipsPlayed,
		&i.ChampionshipsWon,
	)
	return i, err
}

const getTeamStatus = `-- name: GetTeamStatus :one
WITH match_scores AS (
    SELECT
        m.id,
        m.home_team_id,
        m.away_team_id,
        CAST(COALESCE(hg.total, 0) AS INT) AS home_goals,
        CAST(COALESCE(ag.total, 0) AS INT) AS away_goals
    FROM Match m
    LEFT JOIN LATERAL (
        SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
        FROM PlayerStats ps
        JOIN Player p ON p.footballer_id = ps.player_id
        JOIN Footballer f ON f.id = p.footballer_id
        WHERE ps.match_id = m.id AND f.team_id = m.home_team_id
    ) hg ON true
    LEFT JOIN LATERAL (
        SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
        FROM PlayerStats ps
        JOIN Player p ON p.footballer_id = ps.player_id
        JOIN Footballer f ON f.id = p.footballer_id
        WHERE ps.match_id = m.id AND f.team_id = m.away_team_id
    ) ag ON true
    WHERE m.season_id = $2
)
SELECT
    t.id AS team_id,
    t.name,
    COUNT(CASE WHEN ms.home_team_id = t.id AND ms.home_goals > ms.away_goals THEN 1 END) AS home_wins,
    COUNT(CASE WHEN ms.home_team_id = t.id AND ms.home_goals = ms.away_goals THEN 1 END) AS home_draws,
    COUNT(CASE WHEN ms.home_team_id = t.id AND ms.home_goals < ms.away_goals THEN 1 END) AS home_losses,
    COUNT(CASE WHEN ms.away_team_id = t.id AND ms.away_goals > ms.home_goals THEN 1 END) AS away_wins,
    COUNT(CASE WHEN ms.away_team_id = t.id AND ms.away_goals = ms.home_goals THEN 1 END) AS away_draws,
    COUNT(CASE WHEN ms.away_team_id = t.id AND ms.away_goals < ms.home_goals THEN 1 END) AS away_losses,
    COUNT(CASE WHEN (ms.home_team_id = t.id AND ms.home_goals > ms.away_goals) OR (ms.away_team_id = t.id AND ms.away_goals > ms.home_goals) THEN 1 END) AS total_wins,
    COUNT(CASE WHEN ms.home_goals = ms.away_goals AND (ms.home_team_id = t.id OR ms.away_team_id = t.id) THEN 1 END) AS total_draws,
    COUNT(CASE WHEN (ms.home_team_id = t.id AND ms.home_goals < ms.away_goals) OR (ms.away_team_id = t.id AND ms.away_goals < ms.home_goals) THEN 1 END) AS total_losses
FROM Team t
LEFT JOIN match_scores ms ON ms.home_team_id = t.id OR ms.away_team_id = t.id
WHERE t.id = $1
GROUP BY t.id, t.name
`

type GetTeamStatusParams struct {
	ID       int64
	SeasonID sql.NullInt64
}

type GetTeamStatusRow struct {
	TeamID      int64
	Name        string
	HomeWins    int64
	HomeDraws   int64
	HomeLosses  int64
	AwayWins    int64
	AwayDraws   int64
	AwayLosses  int64
	TotalWins   int64
	TotalDraws  int64
	TotalLosses int64
}

// Report 6: team status
func (q *Queries) GetTeamStatus(ctx context.Context, arg GetTeamStatusParams) (GetTeamStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getTeamStatus, arg.ID, arg.SeasonID)
	var i GetTeamStatusRow
	err := row.Scan(
		&i.TeamID,
		&i.Name,
		&i.HomeWins,
		&i.HomeDraws,
		&i.HomeLosses,
		&i.AwayWins,
		&i.AwayDraws,
		&i.AwayLosses,
		&i.TotalWins,
		&i.TotalDraws,
		&i.TotalLosses,
	)
	return i, err
}

const listCoaches = `-- name: ListCoaches :many
SELECT f.id, f.team_id, f.name, f.number, f.years_in_team,
       c.experience_years, c.championships_won
FROM Footballer f
JOIN Coach c ON c.footballer_id = f.id
ORDER BY f.id
`

type ListCoachesRow struct {
	ID               int64
	TeamID           sql.NullInt64
	Name             string
	Number           sql.NullInt32
	YearsInTeam      sql.NullInt32
	ExperienceYears  sql.NullInt32
	ChampionshipsWon sql.NullInt32
}

func (q *Queries) ListCoaches(ctx context.Context) ([]ListCoachesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCoaches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoachesRow
	for rows.Next() {
		var i ListCoachesRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Number,
			&i.YearsInTeam,
			&i.ExperienceYears,
			&i.ChampionshipsWon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoachesByTeam = `-- name: ListCoachesByTeam :many
SELECT f.id, f.team_id, f.name, f.number, f.years_in_team,
       c.experience_years, c.championships_won
FROM Footballer f
JOIN Coach c ON c.footballer_id = f.id
WHERE f.team_id = $1
ORDER BY f.id
`

type ListCoachesByTeamRow struct {
	ID               int64
	TeamID           sql.NullInt64
	Name             string
	Number           sql.NullInt32
	YearsInTeam      sql.NullInt32
	ExperienceYears  sql.NullInt32
	ChampionshipsWon sql.NullInt32
}

func (q *Queries) ListCoachesByTeam(ctx context.Context, teamID sql.NullInt64) ([]ListCoachesByTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, listCoachesByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoachesByTeamRow
	for rows.Next() {
		var i ListCoachesByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Number,
			&i.YearsInTeam,
			&i.ExperienceYears,
			&i.ChampionshipsWon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoachesByExperience = `-- name: ListCoachesByExperience :many
SELECT
    f.name,
    f.number,
    c.experience_years,
    c.championships_won,
    t.name AS team_name
FROM Footballer f
JOIN Coach c ON c.footballer_id = f.id
LEFT JOIN Team t ON t.id = f.team_id
ORDER BY c.championships_won DESC, c.experience_years DESC, f.name
`

type ListCoachesByExperienceRow struct {
	Name             string
	Number           sql.NullInt32
	ExperienceYears  sql.NullInt32
	ChampionshipsWon sql.NullInt32
	TeamName         sql.NullString
}

// Report 4: coaches by experience
func (q *Queries) ListCoachesByExperience(ctx context.Context) ([]ListCoachesByExperienceRow, error) {
	rows, err := q.db.QueryContext(ctx, listCoachesByExperience)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoachesByExperienceRow
	for rows.Next() {
		var i ListCoachesByExperienceRow
		if err := rows.Scan(
			&i.Name,
			&i.Number,
			&i.ExperienceYears,
			&i.ChampionshipsWon,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatches = `-- name: ListMatches :many
SELECT
    m.id, m.home_team_id, m.away_team_id, m.season_id, m.stadium_id, m.match_date, m.attendance, m.disputed,
    CAST(COALESCE(hg.total, 0) AS INT) AS home_goals,
    CAST(COALESCE(ag.total, 0) AS INT) AS away_goals
FROM Match m
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.home_team_id
) hg ON true
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.away_team_id
) ag ON true
ORDER BY m.match_date, m.id
`

type ListMatchesRow struct {
	ID         int64
	HomeTeamID sql.NullInt64
	AwayTeamID sql.NullInt64
	SeasonID   sql.NullInt64
	StadiumID  sql.NullInt64
	MatchDate  time.Time
	Attendance sql.NullInt32
	Disputed   bool
	HomeGoals  int32
	AwayGoals  int32
}

func (q *Queries) ListMatches(ctx context.Context) ([]ListMatchesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesRow
	for rows.Next() {
		var i ListMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.SeasonID,
			&i.StadiumID,
			&i.MatchDate,
			&i.Attendance,
			&i.Disputed,
			&i.HomeGoals,
			&i.AwayGoals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesBetweenTeams = `-- name: ListMatchesBetweenTeams :many
SELECT
    m.id,
    m.match_date,
    s.name AS stadium_name,
    ht.name AS home_team_name,
    at.name AS away_team_name,
    CAST(COALESCE(hg.total, 0) AS INT) AS home_goals,
    CAST(COALESCE(ag.total, 0) AS INT) AS away_goals,
    COALESCE((
        SELECT SUM(ps.assists)
        FROM PlayerStats ps
        JOIN Player p ON p.footballer_id = ps.player_id
        JOIN Footballer f ON f.id = p.footballer_id
        WHERE ps.match_id = m.id AND f.team_id = m.home_team_id
    ), 0) AS home_assists,
    COALESCE((
        SELECT SUM(ps.assists)
        FROM PlayerStats ps
        JOIN Player p ON p.footballer_id = ps.player_id
        JOIN Footballer f ON f.id = p.footballer_id
        WHERE ps.match_id = m.id AND f.team_id = m.away_team_id
    ), 0) AS away_assists
FROM Match m
JOIN Team ht ON m.home_team_id = ht.id
JOIN Team at ON m.away_team_id = at.id
JOIN Stadium s ON m.stadium_id = s.id
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.home_team_id
) hg ON true
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.away_team_id
) ag ON true
WHERE ((m.home_team_id = $1 AND m.away_team_id = $2) OR (m.home_team_id = $2 AND m.away_team_id = $1))
  AND m.season_id = $3
ORDER BY m.match_date, m.id
`

type ListMatchesBetweenTeamsParams struct {
	HomeTeamID sql.NullInt64
	AwayTeamID sql.NullInt64
	SeasonID   sql.NullInt64
}

type ListMatchesBetweenTeamsRow struct {
	ID           int64
	MatchDate    time.Time
	StadiumName  string
	HomeTeamName string
	AwayTeamName string
	HomeGoals    int32
	AwayGoals    int32
	HomeAssists  interface{}
	AwayAssists  interface{}
}

// Report 2: matches between teams
func (q *Queries) ListMatchesBetweenTeams(ctx context.Context, arg ListMatchesBetweenTeamsParams) ([]ListMatchesBetweenTeamsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMatchesBetweenTeams, arg.HomeTeamID, arg.AwayTeamID, arg.SeasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesBetweenTeamsRow
	for rows.Next() {
		var i ListMatchesBetweenTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchDate,
			&i.StadiumName,
			&i.HomeTeamName,
			&i.AwayTeamName,
			&i.HomeGoals,
			&i.AwayGoals,
			&i.HomeAssists,
			&i.AwayAssists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesBetweenTeamsAllSeasons = `-- name: ListMatchesBetweenTeamsAllSeasons :many
SELECT
    m.id,
    m.match_date,
    s.name AS stadium_name,
    ht.name AS home_team_name,
    at.name AS away_team_name,
    CAST(COALESCE(hg.total, 0) AS INT) AS home_goals,
    CAST(COALESCE(ag.total, 0) AS INT) AS away_goals,
    COALESCE((
        SELECT SUM(ps.assists)
        FROM PlayerStats ps
        JOIN Player p ON p.footballer_id = ps.player_id
        JOIN Footballer f ON f.id = p.footballer_id
        WHERE ps.match_id = m.id AND f.team_id = m.home_team_id
    ), 0) AS home_assists,
    COALESCE((
        SELECT SUM(ps.assists)
        FROM PlayerStats ps
        JOIN Player p ON p.footballer_id = ps.player_id
        JOIN Footballer f ON f.id = p.footballer_id
        WHERE ps.match_id = m.id AND f.team_id = m.away_team_id
    ), 0) AS away_assists
FROM Match m
JOIN Team ht ON m.home_team_id = ht.id
JOIN Team at ON m.away_team_id = at.id
JOIN Stadium s ON m.stadium_id = s.id
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.home_team_id
) hg ON true
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.away_team_id
) ag ON true
WHERE (m.home_team_id = $1 AND m.away_team_id = $2) OR (m.home_team_id = $2 AND m.away_team_id = $1)
ORDER BY m.match_date, m.id
`

type ListMatchesBetweenTeamsAllSeasonsParams struct {
	HomeTeamID sql.NullInt64
	AwayTeamID sql.NullInt64
}

type ListMatchesBetweenTeamsAllSeasonsRow struct {
	ID           int64
	MatchDate    time.Time
	StadiumName  string
	HomeTeamName string
	AwayTeamName string
	HomeGoals    int32
	AwayGoals    int32
	HomeAssists  interface{}
	AwayAssists  interface{}
}

func (q *Queries) ListMatchesBetweenTeamsAllSeasons(ctx context.Context, arg ListMatchesBetweenTeamsAllSeasonsParams) ([]ListMatchesBetweenTeamsAllSeasonsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMatchesBetweenTeamsAllSeasons, arg.HomeTeamID, arg.AwayTeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesBetweenTeamsAllSeasonsRow
	for rows.Next() {
		var i ListMatchesBetweenTeamsAllSeasonsRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchDate,
			&i.StadiumName,
			&i.HomeTeamName,
			&i.AwayTeamName,
			&i.HomeGoals,
			&i.AwayGoals,
			&i.HomeAssists,
			&i.AwayAssists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesByDate = `-- name: ListMatchesByDate :many
SELECT
    m.id, m.home_team_id, m.away_team_id, m.season_id, m.stadium_id, m.match_date, m.attendance, m.disputed,
    CAST(COALESCE(hg.total, 0) AS INT) AS home_goals,
    CAST(COALESCE(ag.total, 0) AS INT) AS away_goals
FROM Match m
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.home_team_id
) hg ON true
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.away_team_id
) ag ON true
WHERE m.match_date = $1
ORDER BY m.id
`

type ListMatchesByDateRow struct {
	ID         int64
	HomeTeamID sql.NullInt64
	AwayTeamID sql.NullInt64
	SeasonID   sql.NullInt64
	StadiumID  sql.NullInt64
	MatchDate  time.Time
	Attendance sql.NullInt32
	Disputed   bool
	HomeGoals  int32
	AwayGoals  int32
}

func (q *Queries) ListMatchesByDate(ctx context.Context, matchDate time.Time) ([]ListMatchesByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listMatchesByDate, matchDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesByDateRow
	for rows.Next() {
		var i ListMatchesByDateRow
		if err := rows.Scan(
			&i.ID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.SeasonID,
			&i.StadiumID,
			&i.MatchDate,
			&i.Attendance,
			&i.Disputed,
			&i.HomeGoals,
			&i.AwayGoals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesByDateAndStadium = `-- name: ListMatchesByDateAndStadium :many
SELECT
    m.id, m.home_team_id, m.away_team_id, m.season_id, m.stadium_id, m.match_date, m.attendance, m.disputed,
    CAST(COALESCE(hg.total, 0) AS INT) AS home_goals,
    CAST(COALESCE(ag.total, 0) AS INT) AS away_goals
FROM Match m
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.home_team_id
) hg ON true
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.away_team_id
) ag ON true
WHERE m.match_date = $1 AND m.stadium_id = $2
ORDER BY m.id
`

type ListMatchesByDateAndStadiumParams struct {
	MatchDate time.Time
	StadiumID sql.NullInt64
}

type ListMatchesByDateAndStadiumRow struct {
	ID         int64
	HomeTeamID sql.NullInt64
	AwayTeamID sql.NullInt64
	SeasonID   sql.NullInt64
	StadiumID  sql.NullInt64
	MatchDate  time.Time
	Attendance sql.NullInt32
	Disputed   bool
	HomeGoals  int32
	AwayGoals  int32
}

func (q *Queries) ListMatchesByDateAndStadium(ctx context.Context, arg ListMatchesByDateAndStadiumParams) ([]ListMatchesByDateAndStadiumRow, error) {
	rows, err := q.db.QueryContext(ctx, listMatchesByDateAndStadium, arg.MatchDate, arg.StadiumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesByDateAndStadiumRow
	for rows.Next() {
		var i ListMatchesByDateAndStadiumRow
		if err := rows.Scan(
			&i.ID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.SeasonID,
			&i.StadiumID,
			&i.MatchDate,
			&i.Attendance,
			&i.Disputed,
			&i.HomeGoals,
			&i.AwayGoals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesBySeason = `-- name: ListMatchesBySeason :many
SELECT
    m.id, m.home_team_id, m.away_team_id, m.season_id, m.stadium_id, m.match_date, m.attendance, m.disputed,
    CAST(COALESCE(hg.total, 0) AS INT) AS home_goals,
    CAST(COALESCE(ag.total, 0) AS INT) AS away_goals
FROM Match m
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.home_team_id
) hg ON true
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.away_team_id
) ag ON true
WHERE m.season_id = $1
ORDER BY m.match_date, m.id
`

type ListMatchesBySeasonRow struct {
	ID         int64
	HomeTeamID sql.NullInt64
	AwayTeamID sql.NullInt64
	SeasonID   sql.NullInt64
	StadiumID  sql.NullInt64
	MatchDate  time.Time
	Attendance sql.NullInt32
	Disputed   bool
	HomeGoals  int32
	AwayGoals  int32
}

func (q *Queries) ListMatchesBySeason(ctx context.Context, seasonID sql.NullInt64) ([]ListMatchesBySeasonRow, error) {
	rows, err := q.db.QueryContext(ctx, listMatchesBySeason, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesBySeasonRow
	for rows.Next() {
		var i ListMatchesBySeasonRow
		if err := rows.Scan(
			&i.ID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.SeasonID,
			&i.StadiumID,
			&i.MatchDate,
			&i.Attendance,
			&i.Disputed,
			&i.HomeGoals,
			&i.AwayGoals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesByTeam = `-- name: ListMatchesByTeam :many
SELECT
    m.id, m.home_team_id, m.away_team_id, m.season_id, m.stadium_id, m.match_date, m.attendance, m.disputed,
    CAST(COALESCE(hg.total, 0) AS INT) AS home_goals,
    CAST(COALESCE(ag.total, 0) AS INT) AS away_goals
FROM Match m
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.home_team_id
) hg ON true
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.away_team_id
) ag ON true
WHERE m.home_team_id = $1 OR m.away_team_id = $1
ORDER BY m.match_date, m.id
`

type ListMatchesByTeamRow struct {
	ID         int64
	HomeTeamID sql.NullInt64
	AwayTeamID sql.NullInt64
	SeasonID   sql.NullInt64
	StadiumID  sql.NullInt64
	MatchDate  time.Time
	Attendance sql.NullInt32
	Disputed   bool
	HomeGoals  int32
	AwayGoals  int32
}

func (q *Queries) ListMatchesByTeam(ctx context.Context, homeTeamID sql.NullInt64) ([]ListMatchesByTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, listMatchesByTeam, homeTeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesByTeamRow
	for rows.Next() {
		var i ListMatchesByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.SeasonID,
			&i.StadiumID,
			&i.MatchDate,
			&i.Attendance,
			&i.Disputed,
			&i.HomeGoals,
			&i.AwayGoals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesForDate = `-- name: ListMatchesForDate :many
SELECT
    m.id,
    m.match_date,
    s.name AS stadium_name,
    ht.name AS home_team_name,
    at.name AS away_team_name,
    CAST(COALESCE(hg.total, 0) AS INT) AS home_goals,
    CAST(COALESCE(ag.total, 0) AS INT) AS away_goals,
    m.attendance
FROM Match m
JOIN Team ht ON m.home_team_id = ht.id
JOIN Team at ON m.away_team_id = at.id
JOIN Stadium s ON m.stadium_id = s.id
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.home_team_id
) hg ON true
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.away_team_id
) ag ON true
WHERE m.match_date = $1
ORDER BY m.id
`

type ListMatchesForDateRow struct {
	ID           int64
	MatchDate    time.Time
	StadiumName  string
	HomeTeamName string
	AwayTeamName string
	HomeGoals    int32
	AwayGoals    int32
	Attendance   sql.NullInt32
}

// Report 3: matches by date
func (q *Queries) ListMatchesForDate(ctx context.Context, matchDate time.Time) ([]ListMatchesForDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listMatchesForDate, matchDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesForDateRow
	for rows.Next() {
		var i ListMatchesForDateRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchDate,
			&i.StadiumName,
			&i.HomeTeamName,
			&i.AwayTeamName,
			&i.HomeGoals,
			&i.AwayGoals,
			&i.Attendance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesForDateAndStadium = `-- name: ListMatchesForDateAndStadium :many
SELECT
    m.id,
    m.match_date,
    s.name AS stadium_name,
    ht.name AS home_team_name,
    at.name AS away_team_name,
    CAST(COALESCE(hg.total, 0) AS INT) AS home_goals,
    CAST(COALESCE(ag.total, 0) AS INT) AS away_goals,
    m.attendance
FROM Match m
JOIN Team ht ON m.home_team_id = ht.id
JOIN Team at ON m.away_team_id = at.id
JOIN Stadium s ON m.stadium_id = s.id
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.home_team_id
) hg ON true
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.away_team_id
) ag ON true
WHERE m.match_date = $1
  AND m.stadium_id = $2
ORDER BY m.id
`

type ListMatchesForDateAndStadiumParams struct {
	MatchDate time.Time
	StadiumID sql.NullInt64
}

type ListMatchesForDateAndStadiumRow struct {
	ID           int64
	MatchDate    time.Time
	StadiumName  string
	HomeTeamName string
	AwayTeamName string
	HomeGoals    int32
	AwayGoals    int32
	Attendance   sql.NullInt32
}

func (q *Queries) ListMatchesForDateAndStadium(ctx context.Context, arg ListMatchesForDateAndStadiumParams) ([]ListMatchesForDateAndStadiumRow, error) {
	rows, err := q.db.QueryContext(ctx, listMatchesForDateAndStadium, arg.MatchDate, arg.StadiumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesForDateAndStadiumRow
	for rows.Next() {
		var i ListMatchesForDateAndStadiumRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchDate,
			&i.StadiumName,
			&i.HomeTeamName,
			&i.AwayTeamName,
			&i.HomeGoals,
			&i.AwayGoals,
			&i.Attendance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerStats = `-- name: ListPlayerStats :many
SELECT id, player_id, match_id, goals_scored, assists, shots_on_goal, passes_completed, interceptions, tackles, blocks, saves, goals_conceded
FROM PlayerStats
ORDER BY id
`

func (q *Queries) ListPlayerStats(ctx context.Context) ([]Playerstat, error) {
	rows, err := q.db.QueryContext(ctx, listPlayerStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playerstat
	for rows.Next() {
		var i Playerstat
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.MatchID,
			&i.GoalsScored,
			&i.Assists,
			&i.ShotsOnGoal,
			&i.PassesCompleted,
			&i.Interceptions,
			&i.Tackles,
			&i.Blocks,
			&i.Saves,
			&i.GoalsConceded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerStatsByMatch = `-- name: ListPlayerStatsByMatch :many
SELECT id, player_id, match_id, goals_scored, assists, shots_on_goal, passes_completed, interceptions, tackles, blocks, saves, goals_conceded
FROM PlayerStats
WHERE match_id = $1
ORDER BY id
`

func (q *Queries) ListPlayerStatsByMatch(ctx context.Context, matchID sql.NullInt64) ([]Playerstat, error) {
	rows, err := q.db.QueryContext(ctx, listPlayerStatsByMatch, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playerstat
	for rows.Next() {
		var i Playerstat
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.MatchID,
			&i.GoalsScored,
			&i.Assists,
			&i.ShotsOnGoal,
			&i.PassesCompleted,
			&i.Interceptions,
			&i.Tackles,
			&i.Blocks,
			&i.Saves,
			&i.GoalsConceded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayers = `-- name: ListPlayers :many
SELECT f.id, f.team_id, f.name, f.number, f.years_in_team,
       p.position
FROM Footballer f
JOIN Player p ON p.footballer_id = f.id
ORDER BY f.id
`

type ListPlayersRow struct {
	ID          int64
	TeamID      sql.NullInt64
	Name        string
	Number      sql.NullInt32
	YearsInTeam sql.NullInt32
	Position    string
}

func (q *Queries) ListPlayers(ctx context.Context) ([]ListPlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayersRow
	for rows.Next() {
		var i ListPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Number,
			&i.YearsInTeam,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayersByTeam = `-- name: ListPlayersByTeam :many
SELECT f.id, f.team_id, f.name, f.number, f.years_in_team,
       p.position
FROM Footballer f
JOIN Player p ON p.footballer_id = f.id
WHERE f.team_id = $1
ORDER BY f.id
`

type ListPlayersByTeamRow struct {
	ID          int64
	TeamID      sql.NullInt64
	Name        string
	Number      sql.NullInt32
	YearsInTeam sql.NullInt32
	Position    string
}

func (q *Queries) ListPlayersByTeam(ctx context.Context, teamID sql.NullInt64) ([]ListPlayersByTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayersByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayersByTeamRow
	for rows.Next() {
		var i ListPlayersByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Number,
			&i.YearsInTeam,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasons = `-- name: ListSeasons :many
SELECT id, start_date, end_date FROM Season ORDER BY id
`

func (q *Queries) ListSeasons(ctx context.Context) ([]Season, error) {
	rows, err := q.db.QueryContext(ctx, listSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Season
	for rows.Next() {
		var i Season
		if err := rows.Scan(&i.ID, &i.StartDate, &i.EndDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStadiums = `-- name: ListStadiums :many
SELECT id, name, capacity FROM Stadium ORDER BY id
`

func (q *Queries) ListStadiums(ctx context.Context) ([]Stadium, error) {
	rows, err := q.db.QueryContext(ctx, listStadiums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stadium
	for rows.Next() {
		var i Stadium
		if err := rows.Scan(&i.ID, &i.Name, &i.Capacity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStadiumsByAttendance = `-- name: ListStadiumsByAttendance :many
SELECT
    s.id,
    s.name,
    s.capacity,
    COALESCE(SUM(m.attendance), 0) AS total_attendance,
    COUNT(m.id) AS total_matches,
    CASE
        WHEN COALESCE(s.capacity, 0) > 0 AND COUNT(m.id) > 0
        THEN CAST(ROUND(((COALESCE(SUM(m.attendance), 0)::numeric / (COUNT(m.id) * s.capacity)::numeric) * 100)::numeric, 2) AS FLOAT8)
        ELSE 0.0
    END AS attendance_percentage
FROM Stadium s
LEFT JOIN Match m ON s.id = m.stadium_id AND m.season_id = $1
GROUP BY s.id, s.name, s.capacity
ORDER BY attendance_percentage DESC, s.name
`

type ListStadiumsByAttendanceRow struct {
	ID                   int64
	Name                 string
	Capacity             sql.NullInt32
	TotalAttendance      interface{}
	TotalMatches         int64
	AttendancePercentage float64
}

// Report 5: stadiums by attendance
func (q *Queries) ListStadiumsByAttendance(ctx context.Context, seasonID sql.NullInt64) ([]ListStadiumsByAttendanceRow, error) {
	rows, err := q.db.QueryContext(ctx, listStadiumsByAttendance, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStadiumsByAttendanceRow
	for rows.Next() {
		var i ListStadiumsByAttendanceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Capacity,
			&i.TotalAttendance,
			&i.TotalMatches,
			&i.AttendancePercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStandings = `-- name: ListStandings :many
SELECT
    t.id AS team_id,
    t.name,
    COALESCE(SUM(
        CASE
            WHEN m.home_team_id = t.id AND COALESCE(hg.total, 0) > COALESCE(ag.total, 0) THEN 3
            WHEN m.away_team_id = t.id AND COALESCE(ag.total, 0) > COALESCE(hg.total, 0) THEN 3
            WHEN COALESCE(hg.total, 0) = COALESCE(ag.total, 0) AND m.id IS NOT NULL THEN 1
            ELSE 0
        END
    ), 0) AS points
FROM Team t
LEFT JOIN Match m ON (m.home_team_id = t.id OR m.away_team_id = t.id) AND m.season_id = $1
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.home_team_id
) hg ON true
LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(ps.goals_scored), 0) AS total
    FROM PlayerStats ps
    JOIN Player p ON p.footballer_id = ps.player_id
    JOIN Footballer f ON f.id = p.footballer_id
    WHERE ps.match_id = m.id AND f.team_id = m.away_team_id
) ag ON true
GROUP BY t.id, t.name
ORDER BY points DESC, t.name
`

type ListStandingsRow struct {
	TeamID int64
	Name   string
	Points interface{}
}

// Report 1: standings
func (q *Queries) ListStandings(ctx context.Context, seasonID sql.NullInt64) ([]ListStandingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStandings, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStandingsRow
	for rows.Next() {
		var i ListStandingsRow
		if err := rows.Scan(&i.TeamID, &i.Name, &i.Points); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT id, name, province, mascot, color, championships_played, championships_won
FROM Team
ORDER BY id
`

func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Province,
			&i.Mascot,
			&i.Color,
			&i.ChampionshipsPlayed,
			&i.ChampionshipsWon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoachDetails = `-- name: UpdateCoachDetails :exec
UPDATE Coach
SET experience_years = $2, championships_won = $3
WHERE footballer_id = $1
`

type UpdateCoachDetailsParams struct {
	FootballerID     int64
	ExperienceYears  sql.NullInt32
	ChampionshipsWon sql.NullInt32
}

func (q *Queries) UpdateCoachDetails(ctx context.Context, arg UpdateCoachDetailsParams) error {
	_, err := q.db.ExecContext(ctx, updateCoachDetails, arg.FootballerID, arg.ExperienceYears, arg.ChampionshipsWon)
	return err
}

const updateCoachFootballer = `-- name: UpdateCoachFootballer :exec
UPDATE Footballer
SET team_id = $2, name = $3, number = $4, years_in_team = $5
WHERE id = $1
`

type UpdateCoachFootballerParams struct {
	ID          int64
	TeamID      sql.NullInt64
	Name        string
	Number      sql.NullInt32
	YearsInTeam sql.NullInt32
}

func (q *Queries) UpdateCoachFootballer(ctx context.Context, arg UpdateCoachFootballerParams) error {
	_, err := q.db.ExecContext(ctx, updateCoachFootballer,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.Number,
		arg.YearsInTeam,
	)
	return err
}

const updateMatch = `-- name: UpdateMatch :exec
UPDATE Match
SET home_team_id = $2,
    away_team_id = $3,
    season_id = $4,
    stadium_id = $5,
    match_date = $6,
    attendance = $7,
    disputed = $8
WHERE id = $1
`

type UpdateMatchParams struct {
	ID         int64
	HomeTeamID sql.NullInt64
	AwayTeamID sql.NullInt64
	SeasonID   sql.NullInt64
	StadiumID  sql.NullInt64
	MatchDate  time.Time
	Attendance sql.NullInt32
	Disputed   bool
}

func (q *Queries) UpdateMatch(ctx context.Context, arg UpdateMatchParams) error {
	_, err := q.db.ExecContext(ctx, updateMatch,
		arg.ID,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.SeasonID,
		arg.StadiumID,
		arg.MatchDate,
		arg.Attendance,
		arg.Disputed,
	)
	return err
}

const updatePlayerDetails = `-- name: UpdatePlayerDetails :exec
UPDATE Player
SET position = $2
WHERE footballer_id = $1
`

type UpdatePlayerDetailsParams struct {
	FootballerID int64
	Position     string
}

func (q *Queries) UpdatePlayerDetails(ctx context.Context, arg UpdatePlayerDetailsParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerDetails, arg.FootballerID, arg.Position)
	return err
}

const updatePlayerFootballer = `-- name: UpdatePlayerFootballer :exec
UPDATE Footballer
SET team_id = $2, name = $3, number = $4, years_in_team = $5
WHERE id = $1
`

type UpdatePlayerFootballerParams struct {
	ID          int64
	TeamID      sql.NullInt64
	Name        string
	Number      sql.NullInt32
	YearsInTeam sql.NullInt32
}

func (q *Queries) UpdatePlayerFootballer(ctx context.Context, arg UpdatePlayerFootballerParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerFootballer,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.Number,
		arg.YearsInTeam,
	)
	return err
}

const updatePlayerStat = `-- name: UpdatePlayerStat :exec
UPDATE PlayerStats
SET player_id = $2,
    match_id = $3,
    goals_scored = $4,
    assists = $5,
    shots_on_goal = $6,
    passes_completed = $7,
    interceptions = $8,
    tackles = $9,
    blocks = $10,
    saves = $11,
    goals_conceded = $12
WHERE id = $1
`

type UpdatePlayerStatParams struct {
	ID              int64
	PlayerID        sql.NullInt64
	MatchID         sql.NullInt64
	GoalsScored     sql.NullInt32
	Assists         sql.NullInt32
	ShotsOnGoal     sql.NullInt32
	PassesCompleted sql.NullInt32
	Interceptions   sql.NullInt32
	Tackles         sql.NullInt32
	Blocks          sql.NullInt32
	Saves           sql.NullInt32
	GoalsConceded   sql.NullInt32
}

func (q *Queries) UpdatePlayerStat(ctx context.Context, arg UpdatePlayerStatParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerStat,
		arg.ID,
		arg.PlayerID,
		arg.MatchID,
		arg.GoalsScored,
		arg.Assists,
		arg.ShotsOnGoal,
		arg.PassesCompleted,
		arg.Interceptions,
		arg.Tackles,
		arg.Blocks,
		arg.Saves,
		arg.GoalsConceded,
	)
	return err
}

const updateSeason = `-- name: UpdateSeason :exec
UPDATE Season SET start_date = $2, end_date = $3 WHERE id = $1
`

type UpdateSeasonParams struct {
	ID        int64
	StartDate sql.NullTime
	EndDate   sql.NullTime
}

func (q *Queries) UpdateSeason(ctx context.Context, arg UpdateSeasonParams) error {
	_, err := q.db.ExecContext(ctx, updateSeason, arg.ID, arg.StartDate, arg.EndDate)
	return err
}

const updateStadium = `-- name: UpdateStadium :exec
UPDATE Stadium SET name = $2, capacity = $3 WHERE id = $1
`

type UpdateStadiumParams struct {
	ID       int64
	Name     string
	Capacity sql.NullInt32
}

func (q *Queries) UpdateStadium(ctx context.Context, arg UpdateStadiumParams) error {
	_, err := q.db.ExecContext(ctx, updateStadium, arg.ID, arg.Name, arg.Capacity)
	return err
}

const updateTeam = `-- name: UpdateTeam :exec
UPDATE Team
SET name = $2, province = $3, mascot = $4, color = $5, championships_played = $6, championships_won = $7
WHERE id = $1
`

type UpdateTeamParams struct {
	ID                  int64
	Name                string
	Province            sql.NullString
	Mascot              sql.NullString
	Color               sql.NullString
	ChampionshipsPlayed sql.NullInt32
	ChampionshipsWon    sql.NullInt32
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) error {
	_, err := q.db.ExecContext(ctx, updateTeam,
		arg.ID,
		arg.Name,
		arg.Province,
		arg.Mascot,
		arg.Color,
		arg.ChampionshipsPlayed,
		arg.ChampionshipsWon,
	)
	return err
}
