// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const createCoach = `-- name: CreateCoach :one
WITH ins_fut AS (
    INSERT INTO Futbolista (team_id, name, number, years_in_team)
    VALUES ($1, $2, $3, $4)
    RETURNING id
)
INSERT INTO Coach (futbolista_id, experience_years)
SELECT id, $5 FROM ins_fut
RETURNING futbolista_id
`

type CreateCoachParams struct {
	TeamID          sql.NullInt64
	Name            string
	Number          sql.NullInt32
	YearsInTeam     sql.NullInt32
	ExperienceYears sql.NullInt32
}

// Coach CRUD (atomic with transaction via WITH clause)
func (q *Queries) CreateCoach(ctx context.Context, arg CreateCoachParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCoach,
		arg.TeamID,
		arg.Name,
		arg.Number,
		arg.YearsInTeam,
		arg.ExperienceYears,
	)
	var futbolista_id int64
	err := row.Scan(&futbolista_id)
	return futbolista_id, err
}

const createFutbolista = `-- name: CreateFutbolista :one
INSERT INTO Futbolista (team_id, name, number, years_in_team)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateFutbolistaParams struct {
	TeamID      sql.NullInt64
	Name        string
	Number      sql.NullInt32
	YearsInTeam sql.NullInt32
}

// Futbolista (internal, used by Player/Coach)
func (q *Queries) CreateFutbolista(ctx context.Context, arg CreateFutbolistaParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createFutbolista,
		arg.TeamID,
		arg.Name,
		arg.Number,
		arg.YearsInTeam,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createPlayer = `-- name: CreatePlayer :one
WITH ins_fut AS (
    INSERT INTO Futbolista (team_id, name, number, years_in_team)
    VALUES ($1, $2, $3, $4)
    RETURNING id
)
INSERT INTO Player (futbolista_id, position_id, matches_played, goals, assists)
SELECT id, $5, $6, $7, $8 FROM ins_fut
RETURNING futbolista_id
`

type CreatePlayerParams struct {
	TeamID        sql.NullInt64
	Name          string
	Number        sql.NullInt32
	YearsInTeam   sql.NullInt32
	PositionID    sql.NullInt64
	MatchesPlayed sql.NullInt32
	Goals         sql.NullInt32
	Assists       sql.NullInt32
}

// Player CRUD (atomic with transaction via WITH clause)
func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createPlayer,
		arg.TeamID,
		arg.Name,
		arg.Number,
		arg.YearsInTeam,
		arg.PositionID,
		arg.MatchesPlayed,
		arg.Goals,
		arg.Assists,
	)
	var futbolista_id int64
	err := row.Scan(&futbolista_id)
	return futbolista_id, err
}

const createSeason = `-- name: CreateSeason :one
INSERT INTO Season (start_date, end_date)
VALUES ($1, $2)
RETURNING id
`

type CreateSeasonParams struct {
	StartDate sql.NullTime
	EndDate   sql.NullTime
}

// Season CRUD
func (q *Queries) CreateSeason(ctx context.Context, arg CreateSeasonParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSeason, arg.StartDate, arg.EndDate)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createStadium = `-- name: CreateStadium :one
INSERT INTO Stadium (name, capacity)
VALUES ($1, $2)
RETURNING id
`

type CreateStadiumParams struct {
	Name     string
	Capacity sql.NullInt32
}

// Stadium CRUD
func (q *Queries) CreateStadium(ctx context.Context, arg CreateStadiumParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createStadium, arg.Name, arg.Capacity)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO Team (name, province, mascot, color, championships_played, championships_won)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateTeamParams struct {
	Name                string
	Province            sql.NullString
	Mascot              sql.NullString
	Color               sql.NullString
	ChampionshipsPlayed sql.NullInt32
	ChampionshipsWon    sql.NullInt32
}

// Team CRUD
func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTeam,
		arg.Name,
		arg.Province,
		arg.Mascot,
		arg.Color,
		arg.ChampionshipsPlayed,
		arg.ChampionshipsWon,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteCoachRecord = `-- name: DeleteCoachRecord :exec
DELETE FROM Coach WHERE futbolista_id = $1
`

func (q *Queries) DeleteCoachRecord(ctx context.Context, futbolistaID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCoachRecord, futbolistaID)
	return err
}

const deleteFutbolista = `-- name: DeleteFutbolista :exec
DELETE FROM Futbolista WHERE id = $1
`

func (q *Queries) DeleteFutbolista(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFutbolista, id)
	return err
}

const deletePlayerRecord = `-- name: DeletePlayerRecord :exec
DELETE FROM Player WHERE futbolista_id = $1
`

func (q *Queries) DeletePlayerRecord(ctx context.Context, futbolistaID int64) error {
	_, err := q.db.ExecContext(ctx, deletePlayerRecord, futbolistaID)
	return err
}

const deleteSeason = `-- name: DeleteSeason :exec
DELETE FROM Season WHERE id = $1
`

func (q *Queries) DeleteSeason(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSeason, id)
	return err
}

const deleteStadium = `-- name: DeleteStadium :exec
DELETE FROM Stadium WHERE id = $1
`

func (q *Queries) DeleteStadium(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStadium, id)
	return err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM Team WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTeam, id)
	return err
}

const getCoach = `-- name: GetCoach :one
SELECT f.id, f.team_id, f.name, f.number, f.years_in_team,
       c.experience_years
FROM Futbolista f
JOIN Coach c ON c.futbolista_id = f.id
WHERE f.id = $1
`

type GetCoachRow struct {
	ID              int64
	TeamID          sql.NullInt64
	Name            string
	Number          sql.NullInt32
	YearsInTeam     sql.NullInt32
	ExperienceYears sql.NullInt32
}

func (q *Queries) GetCoach(ctx context.Context, id int64) (GetCoachRow, error) {
	row := q.db.QueryRowContext(ctx, getCoach, id)
	var i GetCoachRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Number,
		&i.YearsInTeam,
		&i.ExperienceYears,
	)
	return i, err
}

const getFutbolista = `-- name: GetFutbolista :one
SELECT id, team_id, name, number, years_in_team FROM Futbolista WHERE id = $1
`

func (q *Queries) GetFutbolista(ctx context.Context, id int64) (Futbolistum, error) {
	row := q.db.QueryRowContext(ctx, getFutbolista, id)
	var i Futbolistum
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Number,
		&i.YearsInTeam,
	)
	return i, err
}

const getPlayer = `-- name: GetPlayer :one
SELECT f.id, f.team_id, f.name, f.number, f.years_in_team,
       p.position_id, p.matches_played, p.goals, p.assists
FROM Futbolista f
JOIN Player p ON p.futbolista_id = f.id
WHERE f.id = $1
`

type GetPlayerRow struct {
	ID            int64
	TeamID        sql.NullInt64
	Name          string
	Number        sql.NullInt32
	YearsInTeam   sql.NullInt32
	PositionID    sql.NullInt64
	MatchesPlayed sql.NullInt32
	Goals         sql.NullInt32
	Assists       sql.NullInt32
}

func (q *Queries) GetPlayer(ctx context.Context, id int64) (GetPlayerRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayer, id)
	var i GetPlayerRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Number,
		&i.YearsInTeam,
		&i.PositionID,
		&i.MatchesPlayed,
		&i.Goals,
		&i.Assists,
	)
	return i, err
}

const getSeason = `-- name: GetSeason :one
SELECT id, start_date, end_date FROM Season WHERE id = $1
`

func (q *Queries) GetSeason(ctx context.Context, id int64) (Season, error) {
	row := q.db.QueryRowContext(ctx, getSeason, id)
	var i Season
	err := row.Scan(&i.ID, &i.StartDate, &i.EndDate)
	return i, err
}

const getStadium = `-- name: GetStadium :one
SELECT id, name, capacity FROM Stadium WHERE id = $1
`

func (q *Queries) GetStadium(ctx context.Context, id int64) (Stadium, error) {
	row := q.db.QueryRowContext(ctx, getStadium, id)
	var i Stadium
	err := row.Scan(&i.ID, &i.Name, &i.Capacity)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, province, mascot, color, championships_played, championships_won
FROM Team
WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Province,
		&i.Mascot,
		&i.Color,
		&i.ChampionshipsPlayed,
		&i.ChampionshipsWon,
	)
	return i, err
}

const listCoaches = `-- name: ListCoaches :many
SELECT f.id, f.team_id, f.name, f.number, f.years_in_team,
       c.experience_years
FROM Futbolista f
JOIN Coach c ON c.futbolista_id = f.id
ORDER BY f.id
`

type ListCoachesRow struct {
	ID              int64
	TeamID          sql.NullInt64
	Name            string
	Number          sql.NullInt32
	YearsInTeam     sql.NullInt32
	ExperienceYears sql.NullInt32
}

func (q *Queries) ListCoaches(ctx context.Context) ([]ListCoachesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCoaches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoachesRow
	for rows.Next() {
		var i ListCoachesRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Number,
			&i.YearsInTeam,
			&i.ExperienceYears,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayers = `-- name: ListPlayers :many
SELECT f.id, f.team_id, f.name, f.number, f.years_in_team,
       p.position_id, p.matches_played, p.goals, p.assists
FROM Futbolista f
JOIN Player p ON p.futbolista_id = f.id
ORDER BY f.id
`

type ListPlayersRow struct {
	ID            int64
	TeamID        sql.NullInt64
	Name          string
	Number        sql.NullInt32
	YearsInTeam   sql.NullInt32
	PositionID    sql.NullInt64
	MatchesPlayed sql.NullInt32
	Goals         sql.NullInt32
	Assists       sql.NullInt32
}

func (q *Queries) ListPlayers(ctx context.Context) ([]ListPlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayersRow
	for rows.Next() {
		var i ListPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Number,
			&i.YearsInTeam,
			&i.PositionID,
			&i.MatchesPlayed,
			&i.Goals,
			&i.Assists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasons = `-- name: ListSeasons :many
SELECT id, start_date, end_date FROM Season ORDER BY id
`

func (q *Queries) ListSeasons(ctx context.Context) ([]Season, error) {
	rows, err := q.db.QueryContext(ctx, listSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Season
	for rows.Next() {
		var i Season
		if err := rows.Scan(&i.ID, &i.StartDate, &i.EndDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStadiums = `-- name: ListStadiums :many
SELECT id, name, capacity FROM Stadium ORDER BY id
`

func (q *Queries) ListStadiums(ctx context.Context) ([]Stadium, error) {
	rows, err := q.db.QueryContext(ctx, listStadiums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stadium
	for rows.Next() {
		var i Stadium
		if err := rows.Scan(&i.ID, &i.Name, &i.Capacity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT id, name, province, mascot, color, championships_played, championships_won
FROM Team
ORDER BY id
`

func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Province,
			&i.Mascot,
			&i.Color,
			&i.ChampionshipsPlayed,
			&i.ChampionshipsWon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoachExperience = `-- name: UpdateCoachExperience :exec
UPDATE Coach
SET experience_years = $2
WHERE futbolista_id = $1
`

type UpdateCoachExperienceParams struct {
	FutbolistaID    int64
	ExperienceYears sql.NullInt32
}

func (q *Queries) UpdateCoachExperience(ctx context.Context, arg UpdateCoachExperienceParams) error {
	_, err := q.db.ExecContext(ctx, updateCoachExperience, arg.FutbolistaID, arg.ExperienceYears)
	return err
}

const updateCoachFutbolista = `-- name: UpdateCoachFutbolista :exec
UPDATE Futbolista
SET team_id = $2, name = $3, number = $4, years_in_team = $5
WHERE id = $1
`

type UpdateCoachFutbolistaParams struct {
	ID          int64
	TeamID      sql.NullInt64
	Name        string
	Number      sql.NullInt32
	YearsInTeam sql.NullInt32
}

func (q *Queries) UpdateCoachFutbolista(ctx context.Context, arg UpdateCoachFutbolistaParams) error {
	_, err := q.db.ExecContext(ctx, updateCoachFutbolista,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.Number,
		arg.YearsInTeam,
	)
	return err
}

const updatePlayerFutbolista = `-- name: UpdatePlayerFutbolista :exec
UPDATE Futbolista
SET team_id = $2, name = $3, number = $4, years_in_team = $5
WHERE id = $1
`

type UpdatePlayerFutbolistaParams struct {
	ID          int64
	TeamID      sql.NullInt64
	Name        string
	Number      sql.NullInt32
	YearsInTeam sql.NullInt32
}

func (q *Queries) UpdatePlayerFutbolista(ctx context.Context, arg UpdatePlayerFutbolistaParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerFutbolista,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.Number,
		arg.YearsInTeam,
	)
	return err
}

const updatePlayerStats = `-- name: UpdatePlayerStats :exec
UPDATE Player
SET position_id = $2, matches_played = $3, goals = $4, assists = $5
WHERE futbolista_id = $1
`

type UpdatePlayerStatsParams struct {
	FutbolistaID  int64
	PositionID    sql.NullInt64
	MatchesPlayed sql.NullInt32
	Goals         sql.NullInt32
	Assists       sql.NullInt32
}

func (q *Queries) UpdatePlayerStats(ctx context.Context, arg UpdatePlayerStatsParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerStats,
		arg.FutbolistaID,
		arg.PositionID,
		arg.MatchesPlayed,
		arg.Goals,
		arg.Assists,
	)
	return err
}

const updateSeason = `-- name: UpdateSeason :exec
UPDATE Season SET start_date = $2, end_date = $3 WHERE id = $1
`

type UpdateSeasonParams struct {
	ID        int64
	StartDate sql.NullTime
	EndDate   sql.NullTime
}

func (q *Queries) UpdateSeason(ctx context.Context, arg UpdateSeasonParams) error {
	_, err := q.db.ExecContext(ctx, updateSeason, arg.ID, arg.StartDate, arg.EndDate)
	return err
}

const updateStadium = `-- name: UpdateStadium :exec
UPDATE Stadium SET name = $2, capacity = $3 WHERE id = $1
`

type UpdateStadiumParams struct {
	ID       int64
	Name     string
	Capacity sql.NullInt32
}

func (q *Queries) UpdateStadium(ctx context.Context, arg UpdateStadiumParams) error {
	_, err := q.db.ExecContext(ctx, updateStadium, arg.ID, arg.Name, arg.Capacity)
	return err
}

const updateTeam = `-- name: UpdateTeam :exec
UPDATE Team
SET name = $2, province = $3, mascot = $4, color = $5, championships_played = $6, championships_won = $7
WHERE id = $1
`

type UpdateTeamParams struct {
	ID                  int64
	Name                string
	Province            sql.NullString
	Mascot              sql.NullString
	Color               sql.NullString
	ChampionshipsPlayed sql.NullInt32
	ChampionshipsWon    sql.NullInt32
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) error {
	_, err := q.db.ExecContext(ctx, updateTeam,
		arg.ID,
		arg.Name,
		arg.Province,
		arg.Mascot,
		arg.Color,
		arg.ChampionshipsPlayed,
		arg.ChampionshipsWon,
	)
	return err
}
