import { defineConfig } from "vitepress";
import { creatorCredits } from "./creators";

export default defineConfig({
  lang: "es",
  title: "SoccerLeague",
  description: "Negocio, módulos, arquitectura, datos y operación de SoccerLeague.",
  srcExclude: ["README.md", "Project Specifications.md"],
  cleanUrls: true,
  head: [["link", { rel: "icon", type: "image/svg+xml", href: "/favicon.svg" }]],
  themeConfig: {
    logo: { src: "/favicon.svg", alt: "SoccerLeague" },
    siteTitle: "SoccerLeague · Docs",
    nav: [
      { text: "Negocio", link: "/negocio/contexto" },
      { text: "Módulos", link: "/modulos/" },
      { text: "Arquitectura", link: "/arquitectura/general" },
      { text: "API", link: "/api/contratos" },
      { text: "Operación", link: "/guia/instalacion" },
    ],
    sidebar: [
      { text: "Empezar", items: [
        { text: "Introducción", link: "/guia/introduccion" },
        { text: "Instalación", link: "/guia/instalacion" },
        { text: "Mapa y fuentes", link: "/referencia/mapa" },
      ] },
      { text: "Negocio", collapsed: false, items: [
        { text: "Contexto y alcance", link: "/negocio/contexto" },
        { text: "Procesos", link: "/negocio/procesos" },
        { text: "Reglas e integridad", link: "/negocio/reglas" },
        { text: "Requisitos e implementación", link: "/negocio/requisitos" },
        { text: "Especificación original", link: "/negocio/especificacion-original" },
      ] },
      { text: "Módulos", collapsed: true, items: [
        { text: "Vista general", link: "/modulos/" },
        { text: "Acceso y sesión", link: "/modulos/autenticacion" },
        { text: "Panel y navegación", link: "/modulos/panel" },
        { text: "Usuarios", link: "/modulos/usuarios" },
        { text: "Equipos y plantillas", link: "/modulos/equipos" },
        { text: "Jugadores", link: "/modulos/jugadores" },
        { text: "Entrenadores", link: "/modulos/entrenadores" },
        { text: "Estadios", link: "/modulos/estadios" },
        { text: "Temporadas", link: "/modulos/temporadas" },
        { text: "Partidos", link: "/modulos/partidos" },
        { text: "Estadísticas", link: "/modulos/estadisticas" },
        { text: "Reportes y PDF", link: "/modulos/reportes" },
        { text: "Fórmulas y criterios", link: "/reportes-explicacion" },
      ] },
      { text: "Arquitectura", collapsed: true, items: [
        { text: "Sistema y flujo", link: "/arquitectura/general" },
        { text: "Frontend y capas", link: "/arquitectura/frontend" },
        { text: "Backend y capas", link: "/arquitectura/backend" },
        { text: "Sesión y permisos", link: "/arquitectura/seguridad" },
      ] },
      { text: "Datos", collapsed: true, items: [
        { text: "Modelo y diccionario", link: "/datos/modelo" },
        { text: "Diagrama de relaciones", link: "/database-diagram" },
        { text: "Migraciones y triggers", link: "/datos/migraciones" },
      ] },
      { text: "API", collapsed: true, items: [
        { text: "Contratos", link: "/api/contratos" },
        { text: "Endpoints", link: "/api/endpoints" },
        { text: "Búsqueda y filtros", link: "/api/filtros" },
        { text: "Errores", link: "/api/errores" },
      ] },
      { text: "Operación", collapsed: true, items: [
        { text: "Configuración y primer acceso", link: "/operacion/configuracion" },
        { text: "Desarrollo", link: "/operacion/desarrollo" },
        { text: "Verificación", link: "/operacion/verificacion" },
        { text: "Diagnóstico", link: "/operacion/diagnostico" },
      ] },
      { text: "Diseño y documentación", collapsed: true, items: [
        { text: "Identidad visual y colores", link: "/identidad-visual" },
        { text: "Creadores de la aplicación", link: "/equipo" },
        { text: "Cómo documentar", link: "/guia/documentar" },
        { text: "Límites actuales", link: "/referencia/estado" },
      ] },
    ],
    search: {
      provider: "local",
      options: { translations: {
        button: { buttonText: "Buscar", buttonAriaLabel: "Buscar en la documentación" },
        modal: {
          displayDetails: "Mostrar detalles",
          resetButtonTitle: "Limpiar búsqueda",
          backButtonTitle: "Cerrar búsqueda",
          noResultsText: "No se encontraron resultados para",
          footer: { selectText: "seleccionar", navigateText: "navegar", closeText: "cerrar" },
        },
      } },
    },
    outline: { level: [2, 3], label: "En esta página" },
    docFooter: { prev: "Anterior", next: "Siguiente" },
    sidebarMenuLabel: "Menú",
    returnToTopLabel: "Volver arriba",
    darkModeSwitchLabel: "Apariencia",
    lightModeSwitchTitle: "Cambiar a tema claro",
    darkModeSwitchTitle: "Cambiar a tema oscuro",
    skipToContentLabel: "Ir al contenido",
    footer: {
      message: `Creado por ${creatorCredits}<br><a href="/equipo">Conoce al equipo de SoccerLeague</a>`,
      copyright: `© ${new Date().getFullYear()} SoccerLeague. Todos los derechos reservados.`,
    },
  },
});
