DROP TABLE IF EXISTS Coach;
DROP TABLE IF EXISTS Player;
DROP TABLE IF EXISTS Position;
DROP TABLE IF EXISTS Futbolista;
DROP TABLE IF EXISTS Season;
DROP TABLE IF EXISTS Stadium;
DROP TABLE IF EXISTS Team;
